import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


class SHA 
{
	public static String getSHA(String input) throws NoSuchAlgorithmException
	{
		// Static getInstance method is called with hashing SHA
		MessageDigest md = MessageDigest.getInstance("SHA-256");

		// digest() method called
		// to calculate message digest of an input
	    byte[] messageDigest = md.digest(input.getBytes());

        // Convert byte array into signum representation
        BigInteger no = new BigInteger(1, messageDigest);

        // Convert message digest into hex value
        String hashtext = no.toString(16);

        while (hashtext.length() < 64) 
        {
            hashtext = "0" + hashtext;
        }
        
        return hashtext;
    }

	public static void main(String args[]) throws NoSuchAlgorithmException
	{
		String s = "Hello world !";
        
		System.out.println("HashCode Generated by SHA is: " + getSHA(s));
	}
}
